# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_issue_repro',
                'doc_host': 'https://Isaac-Flath.github.io',
                'git_url': 'https://github.com/Isaac-Flath/nbdev_issue_repro',
                'lib_path': 'nbdev_issue_repro'},
  'syms': {'nbdev_issue_repro.core': {'nbdev_issue_repro.core.foo': ('core.html#foo', 'nbdev_issue_repro/core.py')}}}
